### ISSUE TITLE
Vault KV v1

### ISSUE THREAD

**Issue by chi110r** [pbchekin/vault-sync#8]
Hi,
first of all nice work!
my question, the syncer only works with the KV Secret engine v2?

is there a way to implement working with KV Secret engine v1

**Comment by pbchekin** [comment]
Currently v1 is not supported by the Vault client library (https://crates.io/crates/hashicorp_vault/), but I will take a look if that can be fixed.

**Comment by pbchekin** [comment]
Hi @chi110r , version 0.9.1 supports KV v1 for source and destination Vaults. Now you can specify a version for the secrets engine (see https://github.com/ChrisMacNaughton/vault-rs), by default the version is 2. I will take a look if the engine version can be detected automatically.
